CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD CONSTRAINT users_username_unique UNIQUE(username);
ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE(email);

CREATE TABLE IF NOT EXISTS categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255)
);

ALTER TABLE categories ADD CONSTRAINT categories_name_unique UNIQUE(name);

CREATE TABLE IF NOT EXISTS videos(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    url VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_public BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS video_likes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    like_value SMALLINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE video_likes ADD CONSTRAINT video_likes_user_id_video_id_unique UNIQUE(user_id, video_id);

CREATE TABLE IF NOT EXISTS video_views(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL,
    user_id BIGINT,
    ip_address VARCHAR(100),
    viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(500) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked BOOLEAN DEFAULT FALSE
);

ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_token_unique UNIQUE(token);

-- Foreign keys
ALTER TABLE video_likes ADD CONSTRAINT video_likes_video_id_foreign FOREIGN KEY(video_id) REFERENCES videos(id);
ALTER TABLE video_likes ADD CONSTRAINT video_likes_user_id_foreign FOREIGN KEY(user_id) REFERENCES users(id);
ALTER TABLE video_views ADD CONSTRAINT video_views_user_id_foreign FOREIGN KEY(user_id) REFERENCES users(id);
ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_user_id_foreign FOREIGN KEY(user_id) REFERENCES users(id);
ALTER TABLE videos ADD CONSTRAINT videos_user_id_foreign FOREIGN KEY(user_id) REFERENCES users(id);
ALTER TABLE video_views ADD CONSTRAINT video_views_video_id_foreign FOREIGN KEY(video_id) REFERENCES videos(id);
-- ALTER TABLE videos ADD CONSTRAINT videos_category_id_foreign FOREIGN KEY(category_id) REFERENCES categories(id);